[build]
  buildCommand = "cd backend && bundle install"

[deploy]
  startCommand = "cd backend && ./bin/railway-start"
  restartPolicyType = "on_failure"

[[services]]
  name = "backend"
  source = "backend"