[build]
  buildCommand = "cd backend && bundle install && rails assets:precompile"

[deploy]
  startCommand = "cd backend && rails server -b 0.0.0.0 -p $PORT"
  restartPolicyType = "on_failure"

[[services]]
  name = "backend"
  source = "backend"